package com.example.getmyparking.models

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.example.getmyparking.utils.enums.*

data class Parking(
    val id:Int,
    val city:String,
    val name:String,
    val displayName:String,
    val address:String,
    val landmark:String,
    val category:ParkingCategory,
    val type:ParkingType,
    val ownership:ParkingOwnership,
    val gateType:GateType,
    val geoLocation:GeoLocation,
    val feeType:ParkingFeeType,
    val entrancePhoto:String,
    val entrancePhotoAdditional:String,
    val structure:ParkingStructure,
    val heightRestriction:String,
    val noFloors:Int,
    val surfaceType:String,
    val cctvInstalled:Int,
    val powerSupplyAvailable:Int,
    val ticketingSystem: TicketingSystem,
    val ticketingSystemCompany:String,
    val sameOperationalHours:Int,
    val operationalHourNotes:String,
    val countryCode:Int,
    val region:String,
    val zipCode:Int,
    val webUrl:String,
    val description:String,
    val areaPhoto:String,
    val areaPhoto2:String,
    val receiptPhoto:String,
    val weekdayAverage:Int,
    val weekendAverage:Int,
    val extraPhoto:String,
    val lastUpdateBy:String,
    val isParkingEnabled:Int,
    val externalId:Int,
    val cpmsKey:String,
    val parkingLots: List<ParkingLot>,
    val contractorInfo: ContractorInfo,
    val operationalHours: List<OperationalHours>,
    val paymentMethods : List<PaymentMethodType>,
    val parkingTranslations : Any,
    val discounts: List<String>,
    val services: List <String>,
    val publicTransportOptionTypes: List<String>
)
