package com.example.getmyparking.models

data class Parking(
    val id:Int,
    val city:String,
    val name:String,
    val displayName:String,
    val address:String,
    val landmark:String,
    val category:String,
    val type:String,
    val ownership:String,
    val gateType:String,
    val geoLocation:GeoLocation,
    val feeType:String,
    val entrancePhoto:String,
    val entrancePhotoAdditional:String?,
    val structure:String,
    val heightRestriction:String?,
    val noFloors:String?,
    val surfaceType:String,
    val cctvInstalled:Int,
    val powerSupplyAvailable:Int,
    val ticketingSystem:String,
    val ticketingSystemCompany:String?,
    val sameOperationalHours:Int,
    val operationalHourNotes:String?,
    val countryCode:Int?,
    val region:String?,
    val zipCode:Int?,
    val webUrl:String?,
    val description:String?,
    val areaPhoto:String,
    val areaPhoto2:String,
    val receiptPhoto:String?,
    val weekdayAverage:Int,
    val weekendAverage:Int,
    val extraPhoto:String,
    val lastUpdateBy:String,
    val isParkingEnabled:Boolean,
    val externalId:Int?,
    val cpmsKey:String,
    val parkingLots: List<ParkingLot>
)
